apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-static1
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 590779969216.dkr.ecr.us-east-2.amazonaws.com/k8s-static1: 1

        ports:
        - containerPort: 80
